tap "homebrew/core"
tap "homebrew/cask"
brew "ack"
brew "chruby"
brew "chruby-fish"
brew "fish"
brew "git"
brew "hub"
brew "nvm"
cask "discord"
cask "google-chrome"
cask "slack"
cask "telegram"
cask "transmission"
cask "visual-studio-code"
cask "whatsapp"
mas "Xcode", id: 497799835
