#!/bin/sh

touch config/fish/credentials.fish

FISH=$(which fish)

if ! grep -q "$FISH" /etc/shells; then
  echo $FISH | sudo tee -a /etc/shells
fi

if [ "$SHELL" != "$FISH" ]
then
  sudo chsh -s $FISH $USER
fi
